adrj_homepage:
    pattern:  /
    defaults: { _controller: AdrjBundle:Default:index }

blog_page:
    pattern: /blog
    defaults: { _controller: AdrjBundle:Blog:blog }

blog_show_post:
    pattern: /blog/show/{id}
    defaults: { _controller: AdrjBundle:Blog:show }

works_page:
    pattern: /works
    defaults: { _controller: AdrjBundle:Works:works }

works_list:
    pattern: /works/{category}
    defaults: { _controller: AdrjBundle:Works:list }

works_show_work:
    pattern: /works/{category}/show/{id_name}
    defaults: { _controller: AdrjBundle:Works:show }

files_access:
    pattern: /files
    defaults: { _controller: AdrjBundle:Files:access }

files_show_list:
    pattern: /files/{token}
    defaults: { _controller: AdrjBundle:Files:show }