adrj_homepage:
    pattern:  /
    defaults: { _controller: AdrjBundle:Default:index }

blog:
    pattern: /blog
    defaults: { _controller: AdrjBundle:Blog:blog }

show:
    pattern: /blog/show/{id}
    defaults: { _controller: AdrjBundle:Blog:show }

works:
    pattern: /works
    defaults: { _controller: AdrjBundle:Works:works }

list:
    pattern: /works/{category}
    defaults: { _controller: AdrjBundle:Works:list }

show:
    pattern: /works/{category}/show/{id_name}
    defaults: { _controller: AdrjBundle:Works:show }

access:
    pattern: /files
    defaults: { _controller: AdrjBundle:Files:access }

show:
    pattern: /files/{token}
    defaults: { _controller: AdrjBundle:Files:show }