<?php

namespace Adrj\AdrjFilesBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FilesTokensRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FilesTokensRepository extends EntityRepository
{
    public function findByToken($token)
    {
        $queryBuilder = $this->createQueryBuilder('t')
        ->where('t.token = :token')
        ->setParameter('token', $token);

        $query = $queryBuilder->getQuery();
        return $query->getResult();
    }
}
