<?php

namespace Adrj\AdrjFilesBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FilesListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FilesListRepository extends EntityRepository
{
    public function findByTokenId($tokenId)
    {
        $queryBuilder = $this->createQueryBuilder('f')
        ->where('f.tokenId = :tokenId')
        ->setParameter('tokenId', $tokenId);

        $query = $queryBuilder->getQuery();
        return $query->getResult();
    }
}
