adrj:
    resource: "@AdrjBundle/Resources/config/routing.yml"
    prefix: /

login:
    path: /login
    defaults: { _controller: AdrjBundle:Default:login }

login_check:
    path: /login_check

logout:
    path: /logout

adrj_files:
    resource: "@AdrjFilesBundle/Resources/config/routing.yml"
    prefix: /files

adrj_works:
    resource: "@AdrjWorksBundle/Resources/config/routing.yml"
    prefix: /works

adrj_blog:
    resource: "@AdrjBlogBundle/Resources/config/routing.yml"
    prefix: /blog
    
adrj_api:
    defaults: { _controller: AdrjBundle:Default:apiInfo }
    path: /api
    