parameters:
#    adrj_works.example.class: Adrj\AdrjWorksBundle\Example

services:
#    adrj_works.example:
#        class: %adrj_works.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
