parameters:
#    adrj_blog.example.class: Adrj\AdrjBlogBundle\Example

services:
#    adrj_blog.example:
#        class: %adrj_blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
