<?php

namespace Adrj\AdrjBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BlogPostsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlogPostsRepository extends EntityRepository
{
    public function getActivePosts()
    {
        $queryBuilder = $this->createQueryBuilder('p')
        ->where('p.active = true')
        ->orderBy('p.createTime','DESC');

        $query = $queryBuilder->getQuery();
        return $query->getResult();
    }

    public function getActivePostById($id)
    {
        $queryBuilder = $this->createQueryBuilder('p')
        ->where('p.active = true AND p.id = :index')
        ->setParameter('index', $id);

        $query = $queryBuilder->getQuery();
        return $query->getResult();
    }

    public function addPost($post)
    {

    }

}
