#adrj_files_homepage:
#    pattern:  /hello/{name}
#    defaults: { _controller: AdrjFilesBundle:Default:index }

files_page:
    pattern: /
    defaults: { _controller: AdrjFilesBundle:Files:access }

files_show_list:
    pattern: /show
    defaults: { _controller: AdrjFilesBundle:Files:show }

files_get_file:
    pattern: /get/{fileName}
    defaults: { _controller: AdrjFilesBundle:Files:get }

files_add_file:
    pattern: /add
    defaults: { _controller: AdrjFilesBundle:Files:add }