<?php

namespace Adrj\AdrjWorksBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * WorksListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorksListRepository extends EntityRepository
{
    public function getAllWorks()
    {
        $queryBuilder = $this->createQueryBuilder('w')
        ->select('c, w')
        ->innerJoin('AdrjWorksBundle:WorksCategories', 'c', 'WITH', 'w.categoryId = c.id');

        $query = $queryBuilder->getQuery();
        return $query->getResult();
    }

    public function getWorksByCategory($category)
    {
        $queryBuilder = $this->createQueryBuilder('w')
        ->innerJoin('AdrjWorksBundle:WorksCategories', 'c', 'WITH', 'w.categoryId = c.id')
        ->where('c.name = :category')
        ->setParameter('category', $category);

        $query = $queryBuilder->getQuery();
        return $query->getResult();
    }
}
