<?php

namespace Adrj\AdrjWorksBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * WorksListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorksListRepository extends EntityRepository
{
}
